### ISSUE TITLE
Invalid path pour la carte SD sur Galaxy Note3 Neo (hllte)

### ISSUE THREAD

**Issue by giletvin** [giletvin/ornidroid#122]
java.lang.IllegalArgumentException: Invalid path: /storage/extSdCard/ornidroid/ornidroid
at android.os.StatFs.doStat(StatFs.java:46)
at android.os.StatFs.<init>(StatFs.java:39)
at fr.ornidroid.service.OrnidroidIOServiceImpl.isEnoughFreeSpace(OrnidroidIOServiceImpl.java:624)
at fr.ornidroid.ui.components.AbstractFragment.startDownloadAll(AbstractFragment.java:455)
at fr.ornidroid.ui.components.AbstractFragment$1.onClick(AbstractFragment.java:301)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:170)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5692)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: libcore.io.ErrnoException: statvfs failed: ENOENT (No such file or directory)
at libcore.io.Posix.statvfs(Native Method)
at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:132)
at android.os.StatFs.doStat(StatFs.java:44)
... 13 more

**Comment by giletvin** [comment]
http://stackoverflow.com/questions/23516075/invalid-path-error-get-the-external-memory-size

The suggestion by @sandrstar is correct. My apps experienced the same crash and I've resolved it just by adding READ_EXTERNAL_STORAGE permission. Though it seems crashes for my case only occurred/reported on 4.4 device.
