### ISSUE TITLE
Crash dans la modif OrnidroidHome

### ISSUE THREAD

**Issue by giletvin** [giletvin/ornidroid#130]
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@42075b98 is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:550)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
at android.app.Dialog.show(Dialog.java:286)
at fr.ornidroid.ui.activity.OrnidroidPreferenceActivity.showProgressBar(OrnidroidPreferenceActivity.java:177)
at fr.ornidroid.ui.activity.OrnidroidPreferenceActivity.onSharedPreferenceChanged(OrnidroidPreferenceActivity.java:99)
at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:475)
at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:461)
at fr.ornidroid.ui.components.OrnidroidHomeDialogPreference.saveOrnidroidHomeValue(OrnidroidHomeDialogPreference.java:163)
at fr.ornidroid.ui.components.OrnidroidHomeDialogPreference.onDialogClosed(OrnidroidHomeDialogPreference.java:219)
at android.preference.DialogPreference.onDismiss(DialogPreference.java:383)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1238)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5097)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)

**Comment by giletvin** [comment]
Pb d'affichage de la boite de dialogue quand le processus démarre.
