### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

### ISSUE THREAD

**Issue by giletvin** [giletvin/ornidroid#131]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:154)
at android.app.AlertDialog$Builder.<init>(AlertDialog.java:379)
at fr.ornidroid.ui.fragment.AbstractFragment.onCheckUpdateTaskEnded(AbstractFragment.java:541)
at fr.ornidroid.ui.fragment.AudioFragment_.access$3(AudioFragment_.java:1)
at fr.ornidroid.ui.fragment.AudioFragment_$14.run(AudioFragment_.java:293)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by giletvin** [comment]
cas peu courant, je pense.
